### ISSUE TITLE
`contrastive_model.load_model()` not working with `tf.distribute.MirroredStrategy`

### ISSUE THREAD

**Issue by tomrtk** [tensorflow/similarity#287]
Hi.

When using `contrastive_model.load_model()` within a `tf.distribute.MirroredStrategy` scope, it errors with following traceback:

```console
Traceback (most recent call last):
  File "/.../example.py", line 178, in <module>
    raise SystemExit(main())
  File "/.../example.py", line 170, in main
    model = tfsim.models.contrastive_model.load_model(
  File "/.../.local/lib/python3.9/site-packages/tensorflow_similarity/models/contrasti
ve_model.py", line 106, in load_model
    optimizer.apply_gradients(zip(zero_grads, tvars))
  File "/.../.local/lib/python3.9/site-packages/tensorflow_addons/optimizers/weight_de
cay_optimizers.py", line 189, in apply_gradients
    return super().apply_gradients(grads_and_vars, name=name, **kwargs)
  File "/storage/software/TensorFlow/2.6.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/keras/optimi
zer_v2/optimizer_v2.py", line 636, in apply_gradients
    raise RuntimeError(
RuntimeError: `apply_gradients() cannot be called in cross-replica context. Use `tf.distribute.Strategy.ru
n` to enter replica context.
```

I was looking for a solution with a local `load_model` function and I found a solution working for me, if you are interested.

### failing example code

<details><summary>`example.py`</summary>
<p>

based on example notebook + MirroredStrategy  -- issue is almost at the bottom of the example

```python
import gc
import json
import os
from pathlib import Path

import numpy as np
import tensorflow as tf
import tensorflow_similarity as tfsim
import tensorflow_addons as tfa

IMG_SIZE = 28


def get_projector(input_dim, dim, activation="relu", num_layers: int = 3):
    inputs = tf.keras.layers.Input((input_dim,), name="projector_input")
    x = inputs

    for i in range(num_layers - 1):
        x = tf.keras.layers.Dense(
            dim,
            use_bias=False,
            kernel_initializer=tf.keras.initializers.LecunUniform(),
            name=f"projector_layer_{i}",
        )(x)
        x = tf.keras.layers.BatchNormalization(
            epsilon=1.001e-5, name=f"batch_normalization_{i}",
        )(x)
        x = tf.keras.layers.Activation(
            activation, name=f"{activation}_activation_{i}",
        )(x)
    x = tf.keras.layers.Dense(
        dim,
        use_bias=False,
        kernel_initializer=tf.keras.initializers.LecunUniform(),
        name="projector_output",
    )(x)
    x = tf.keras.layers.BatchNormalization(
        epsilon=1.001e-5,
        center=False,
        scale=False,
        name="batch_normalization_ouput",
    )(x)
    o = tfsim.layers.ActivationStdLoggingLayer(name="proj_std")(x)
    projector = tf.keras.Model(inputs, o, name="projector")
    return projector


def get_predictor(input_dim, hidden_dim=512, activation="relu"):
    inputs = tf.keras.layers.Input(
        shape=(input_dim,), name="predictor_input",
    )
    x = inputs

    x = tf.keras.layers.Dense(
        hidden_dim,
        use_bias=False,
        kernel_initializer=tf.keras.initializers.LecunUniform(),
        name="predictor_layer_0",
    )(x)
    x = tf.keras.layers.BatchNormalization(
        epsilon=1.001e-5, name="batch_normalization_0",
    )(x)
    x = tf.keras.layers.Activation(
        activation, name=f"{activation}_activation_0",
    )(x)

    x = tf.keras.layers.Dense(
        input_dim,
        kernel_initializer=tf.keras.initializers.LecunUniform(),
        name="predictor_output",
    )(x)
    o = tfsim.layers.ActivationStdLoggingLayer(name="pred_std")(x)
    predictor = tf.keras.Model(inputs, o, name="predictor")
    return predictor


@tf.function
def augment(img):
    view1 = tf.repeat(tf.expand_dims(img, axis=-1), 3, axis=-1)
    view1 = tfsim.augmenters.augmentation_utils.cropping.crop_and_resize(
        view1, IMG_SIZE, IMG_SIZE, area_range=(0.2, 1.0),
    )
    view1 = tf.keras.applications.imagenet_utils.preprocess_input(
        view1,
        data_format=None,
        mode='torch',
    )
    view2 = tf.repeat(tf.expand_dims(img, axis=-1), 3, axis=-1)
    view2 = tfsim.augmenters.augmentation_utils.cropping.crop_and_resize(
        view2, IMG_SIZE, IMG_SIZE, area_range=(0.2, 1.0),
    )
    view2 = tf.keras.applications.imagenet_utils.preprocess_input(
        view2,
        data_format=None,
        mode='torch',
    )
    return view1, view2

def main():
    strategy = tf.distribute.MirroredStrategy()

    (x, y), _ = tf.keras.datasets.mnist.load_data()

    # reduce samples for example
    x = x[:1000]

    ALGORITHM = "simsiam"
    BATCH_SIZE_PER_GPU = 32
    BATCH_SIZE = BATCH_SIZE_PER_GPU * strategy.num_replicas_in_sync
    EPOCHS = 1
    DIM = 2048
    STEPS_PER_EPOCH = x.shape[0] // BATCH_SIZE
    WEIGHT_DECAY = 5e-4
    INIT_LR = 5e-2 * int(BATCH_SIZE / 256)

    with strategy.scope():
        backbone = tfsim.architectures.ResNet18Sim(
            (IMG_SIZE, IMG_SIZE, 3),
            include_top=False,
            pooling='avg',
        )
        projector = get_projector(
            input_dim=backbone.output.shape[-1],
            dim=DIM,
            num_layers=2,
        )
        predictor = get_predictor(input_dim=DIM, hidden_dim=512)

        model = tfsim.models.ContrastiveModel(
            backbone=backbone,
            projector=projector,
            predictor=predictor,
        )
        lr_decayed_fn = tf.keras.optimizers.schedules.CosineDecay(
            initial_learning_rate=INIT_LR,
            decay_steps=EPOCHS * STEPS_PER_EPOCH,
        )
        wd_decayed_fn = tf.keras.optimizers.schedules.CosineDecay(
            initial_learning_rate=WEIGHT_DECAY,
            decay_steps=EPOCHS * STEPS_PER_EPOCH,
        )
        optimizer = tfa.optimizers.SGDW(
            learning_rate=lr_decayed_fn, weight_decay=wd_decayed_fn,
            momentum=0.9,
        )
        loss = tfsim.losses.SimSiamLoss(
            projection_type="cosine_distance", name=ALGORITHM,
        )
        model.compile(
            optimizer=optimizer,
            loss=loss,
        )

    # change AutoShard policy.
    options = tf.data.Options()
    options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA  # noqa E501
    ds = tf.data.Dataset.from_tensor_slices(x)
    ds = ds.with_options(options)
    ds = ds.repeat()
    ds = ds.shuffle(8 * BATCH_SIZE)
    ds = ds.map(augment, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(tf.data.AUTOTUNE)

    dist_ds = strategy.experimental_distribute_dataset(ds)

    model.fit(dist_ds, epochs=EPOCHS, steps_per_epoch=STEPS_PER_EPOCH)

    model.save('./runs/models/trained_model')

    del model

    gc.collect()
    tf.keras.backend.clear_session()

    with strategy.scope():
        model = tfsim.models.contrastive_model.load_model(
            './runs/models/trained_model',
        )

    model.fit(dist_ds, epochs=EPOCHS, steps_per_epoch=STEPS_PER_EPOCH)


if __name__ == "__main__":
    raise SystemExit(main())
```

</p>
</details>

**Comment by owenvallis** [comment]
Thanks for raising this. Can you share your local load_modal function? Thanks.

**Comment by tomrtk** [comment]
> Thanks for raising this. Can you share your local load_modal function? Thanks.

I pushed my patch to `load_model` in #296. I also added a test, but it will only fail on master if running on a node with GPU, and fail silently if not. Unsure if there is a easy way to mock it to trigger on a node with only CPU.
